name: Dro2midi Windows build

on:
  - push
  - pull_request

jobs:
  build-sln:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1


      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          vs-version: 16.1

      - name: Build solution
        run: |
          SET CL=-Wno-c++11-narrowing
          cmd /c build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dro2midi-win-x64
          path: dro2midi.exe

